version: "3.1"

services:

#
#
  vault:
    image: "vault:local_build"
    hostname: "vault"
    environment:
      - VAULT_ADDR=https://$SWARM_MASTER_IP:8200
      - CONSUL_SERVER=$SWARM_MASTER_IP
      - VAULT_SKIP_VERIFY=1
      - VAULT_CONFIG=/config/vault.hcl
      - LOG_LEVEL=trace
      - http_proxy
      - https_proxy
      - no_proxy
    ports:
      - "8200:8200"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s
        window: 120s
      placement:
        constraints:
          - node.role == worker
    build:
      context: .
    secrets:
      - source: vault_tls_key
        target: vault_tls_key
        mode: 0644
      - source: vault_tls_cert
        target: vault_tls_cert
        mode: 0644
      - VAULT_GITHUB_TOKEN
      - VAULT_GITHUB_ADMIN_ORG
    command: $SWARM_MASTER_IP:8500 -t 60 -- /usr/local/bin/bootstrap.sh
secrets:
  vault_tls_key:
    external: true
  vault_tls_cert:
    external: true
  VAULT_GITHUB_TOKEN:
    external: true
  VAULT_GITHUB_ADMIN_ORG:
    external: true
