version: "3.1"

services:

#
#
  vault:
    depends_on:
      - consul
    image: "hub.docker.hpecorp.net/dindc/vault:0.1.3"
    hostname: "vault"
    environment:
      - VAULT_ADDR="https://dashboard.docker.hpecorp.net:8200"
      - CONSUL_SERVER
    ports:
      - "8200:8200"
    deploy:
      labels:
        - "com.docker.ucp.access.label=dindc-core"
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s
        window: 120s
      placement:
        constraints:
          - node.role == worker
    secrets:
      - source: vault_tls_key
        target: vault_tls_key
        mode: 0644
      - source: vault_tls_cert
        target: vault_tls_cert
        mode: 0644
    command: "$CONSUL_SERVER:8500 -t 60 -- docker-entrypoint.sh server -config=/config/vault-pro.hcl -log-level=trace"
secrets:
  vault_tls_key:
    external: true
  vault_tls_cert:
    external: true

networks:
  consul_consul-net:
    external: true
